# Generated by Django 4.1.2 on 2022-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PaperRecommend", "0002_paper_delete_tweet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=50)),
                (
                    "paper",
                    models.ManyToManyField(
                        related_name="keywords", to="TextEmotion.paper"
                    ),
                ),
            ],
            options={"db_table": "Keywords",},
        ),
    ]
