# Generated by Django 4.1.2 on 2022-10-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PaperRecommend", "0003_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="keywords",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Keywords",),
    ]
