# Generated by Django 4.1.2 on 2022-10-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.TextField()),
                ('Keywords', models.TextField()),
                ('comment', models.TextField()),
                ('UserID', models.IntegerField()),
                ('retrievetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserPrefer',
            },
        ),
        migrations.CreateModel(
            name='UserViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperId', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('retrievetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserViewRecord',
            },
        ),
    ]
