# Generated by Django 4.1.2 on 2022-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprefer',
            name='PaperID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
